# Generated by Django 2.2.5 on 2019-09-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseid', models.AutoField(db_column='courseid', primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=256)),
                ('students', models.IntegerField()),
                ('info', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('maxdatabases', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studentdatabases',
            fields=[
                ('dbid', models.AutoField(db_column='dbid', primary_key=True, serialize=False)),
                ('databasename', models.TextField()),
                ('course', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'StudentDatabases',
                'db_table': 'studentdatabases',
                'managed': False,
            },
        ),
    ]
