# Generated by Django 2.2.5 on 2019-09-10 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.TextField()),
                ('students', models.IntegerField()),
                ('info', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('maxdatabases', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studentgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbid', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Studentgroup',
                'db_table': 'studentgroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studentdatabases',
            fields=[
                ('dbid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='designapp1.Studentgroup')),
                ('databasename', models.TextField()),
                ('course', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'StudentDatabases',
                'db_table': 'studentdatabases',
                'managed': False,
            },
        ),
    ]
