# Generated by Django 2.2.5 on 2019-09-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roles',
            table='designproject.roles',
        ),
    ]
