# Generated by Django 2.2.5 on 2019-09-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAs',
            fields=[
                ('TAs', models.AutoField(db_column='taid', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'TAs',
                'db_table': 'tas',
                'managed': False,
            },
        ),
    ]
