# Generated by Django 2.2.5 on 2019-09-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designapp1', '0002_auto_20190910_1701'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roles',
            table='roles',
        ),
    ]
